use super::xyz::flatshcards::cards;
// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum KnownRecord {
    #[serde(rename = "xyz.flatshcards.cards#stack")]
    LexiconXyzFlatshcardsCardsStack(Box<cards::StackRecord>),
    #[serde(rename = "xyz.flatshcards.cards#card")]
    LexiconXyzFlatshcardsCardsCard(Box<cards::CardRecord>),
}

impl From<cards::StackRecord> for KnownRecord {
    fn from(record: cards::StackRecord) -> Self {
        KnownRecord::LexiconXyzFlatshcardsCardsStack(Box::new(record))
    }
}
impl From<cards::Stack> for KnownRecord {
    fn from(record: cards::Stack) -> Self {
        KnownRecord::LexiconXyzFlatshcardsCardsStack(Box::new(record.into()))
    }
}
impl From<cards::CardRecord> for KnownRecord {
    fn from(record: cards::CardRecord) -> Self {
        KnownRecord::LexiconXyzFlatshcardsCardsCard(Box::new(record))
    }
}
impl From<cards::Card> for KnownRecord {
    fn from(record: cards::Card) -> Self {
        KnownRecord::LexiconXyzFlatshcardsCardsCard(Box::new(record.into()))
    }
}
#[allow(clippy::from_over_into)]
impl Into<atrium_api::types::Unknown> for KnownRecord {
    fn into(self) -> atrium_api::types::Unknown {
        atrium_api::types::TryIntoUnknown::try_into_unknown(&self).unwrap()
    }
}
