// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `xyz.flatshcards.cards` namespace.
use atrium_api::types::TryFromUnknown;
///a single flashcard
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Card {
    pub back_lang: String,
    pub back_text: String,
    pub created_at: atrium_api::types::string::Datetime,
    pub front_lang: String,
    pub front_text: String,
    pub stack_id: atrium_api::types::string::RecordKey,
}
pub type CardRecord = atrium_api::types::Object<Card>;
impl From<atrium_api::types::Unknown> for Card {
    fn from(value: atrium_api::types::Unknown) -> Self {
        Self::try_from_unknown(value).unwrap()
    }
}
///a stack of flashcards
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Stack {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub back_lang: core::option::Option<String>,
    pub created_at: atrium_api::types::string::Datetime,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub front_lang: core::option::Option<String>,
    pub label: String,
}
pub type StackRecord = atrium_api::types::Object<Stack>;
impl From<atrium_api::types::Unknown> for Stack {
    fn from(value: atrium_api::types::Unknown) -> Self {
        Self::try_from_unknown(value).unwrap()
    }
}
