// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `xyz.flatshcards` namespace.
use atrium_api::types::Collection;
pub mod cards;

#[derive(Debug)]
pub struct Stack;
impl Collection for Stack {
    const NSID: &'static str = "xyz.flatshcards.cards#stack";
    type Record = cards::StackRecord;
}

#[derive(Debug)]
pub struct Card;
impl Collection for Card {
    const NSID: &'static str = "xyz.flatshcards.cards#card";
    type Record = cards::CardRecord;
}
